-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SCHEMA "eshop";
--> statement-breakpoint
CREATE SEQUENCE "eshop"."subcategories_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."employees_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."orders_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."suppliers_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."users_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."products_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."categories_Id_seq" INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."orderdetails_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "eshop"."product_images_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "eshop"."employees" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."employees_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Title" varchar(50) NOT NULL,
	"BirthDate" date,
	"HireDate" date,
	"Address" varchar(50) NOT NULL,
	"City" varchar(30) NOT NULL,
	"SuperiorId" integer,
	"Created" timestamp DEFAULT now(),
	"CreatedBy" text,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "eshop"."categories" (
	"Id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "eshop"."eshop."categories_Id_seq"" INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Created" timestamp DEFAULT now(),
	"CreatedBy" text,
	"LastModified" timestamp with time zone,
	"LastModifiedBy" text,
	"ImageUrl" varchar(200)
);
--> statement-breakpoint
CREATE TABLE "eshop"."orders" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."orders_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"UserId" integer NOT NULL,
	"EmployeeId" integer,
	"TotalPrice" numeric,
	"ShippedDate" timestamp with time zone,
	"ShipperId" integer,
	"ShipCity" varchar(50) NOT NULL,
	"ShipPostalCode" integer,
	"Created" timestamp DEFAULT now(),
	"LastModified" timestamp with time zone,
	"ShipAddress" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "eshop"."users" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."users_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Address" varchar(100),
	"City" varchar(50),
	"PostalCode" integer,
	"Phone" varchar(20),
	"Created" timestamp DEFAULT CURRENT_TIMESTAMP,
	"Username" varchar(50),
	"Email" varchar(50) NOT NULL,
	"PasswordHash" "bytea",
	"PasswordSalt" "bytea",
	"role" varchar
);
--> statement-breakpoint
CREATE TABLE "eshop"."subcategories" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."subcategories_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"CategoryId" integer NOT NULL,
	"Created" timestamp DEFAULT CURRENT_TIMESTAMP,
	"CreatedBy" text,
	"LastModified" timestamp DEFAULT CURRENT_TIMESTAMP,
	"LastModifiedBy" text,
	"ImageUrl" varchar
);
--> statement-breakpoint
CREATE TABLE "eshop"."suppliers" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."suppliers_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Contact" varchar(50) NOT NULL,
	"Address" varchar(50),
	"City" varchar(50),
	"Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "eshop"."orderdetails" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."orderdetails_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"OrderId" integer NOT NULL,
	"ProductId" integer NOT NULL,
	"Price" numeric,
	"Quantity" integer NOT NULL,
	"Created" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "eshop"."product_images" (
	"Id" serial PRIMARY KEY NOT NULL,
	"ProductId" integer NOT NULL,
	"ImageUrl" varchar(200) NOT NULL,
	"IsMain" boolean DEFAULT false,
	"OrderIndex" integer,
	"Created" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "eshop"."products" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eshop"."eshop."products_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Description" varchar(200),
	"Price" numeric,
	"Amount" integer,
	"Sold" integer,
	"IsDeleted" boolean DEFAULT false,
	"CategoryId" integer NOT NULL,
	"SubcategoryId" integer NOT NULL,
	"SupplierId" integer,
	"Created" timestamp with time zone DEFAULT now() NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone,
	"LastModifiedBy" text,
	"Discount" numeric
);
--> statement-breakpoint
CREATE TABLE "eshop"."shippers" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "eshop"."eshop.shippers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"email" varchar(50),
	"phone" varchar
);
--> statement-breakpoint
ALTER TABLE "eshop"."employees" ADD CONSTRAINT "FK_Employees_Employees_SuperiorId" FOREIGN KEY ("SuperiorId") REFERENCES "eshop"."employees"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."orders" ADD CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "eshop"."users"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."orders" ADD CONSTRAINT "FK_Orders_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "eshop"."employees"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."subcategories" ADD CONSTRAINT "FK_Subcategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "eshop"."categories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."orderdetails" ADD CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "eshop"."orders"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."orderdetails" ADD CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "eshop"."products"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."product_images" ADD CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "eshop"."products"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."products" ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "eshop"."categories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."products" ADD CONSTRAINT "FK_Products_Subcategories_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES "eshop"."subcategories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "eshop"."products" ADD CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "eshop"."suppliers"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IX_Employees_SuperiorId" ON "eshop"."employees" USING btree ("SuperiorId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Orders_EmployeeId" ON "eshop"."orders" USING btree ("EmployeeId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Orders_UserId" ON "eshop"."orders" USING btree ("UserId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Subcategories_CategoryId" ON "eshop"."subcategories" USING btree ("CategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_OrderDetails_OrderId" ON "eshop"."orderdetails" USING btree ("OrderId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_OrderDetails_ProductId" ON "eshop"."orderdetails" USING btree ("ProductId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_CategoryId" ON "eshop"."products" USING btree ("CategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_SubcategoryId" ON "eshop"."products" USING btree ("SubcategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_SupplierId" ON "eshop"."products" USING btree ("SupplierId" int4_ops);
*/