-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150) PRIMARY KEY NOT NULL,
	"ProductVersion" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Employees" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Employees_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Title" varchar(50) NOT NULL,
	"BirthDate" date,
	"HireDate" date,
	"Address" varchar(50) NOT NULL,
	"City" varchar(30) NOT NULL,
	"SuperiorId" integer,
	"Photo" "bytea",
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Shippers" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Shippers_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Phone" varchar(30) NOT NULL,
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "AspNetRoles" (
	"Id" text PRIMARY KEY NOT NULL,
	"Name" varchar(256),
	"NormalizedName" varchar(256),
	"ConcurrencyStamp" text
);
--> statement-breakpoint
CREATE TABLE "AspNetRoleClaims" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""AspNetRoleClaims_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"RoleId" text NOT NULL,
	"ClaimType" text,
	"ClaimValue" text
);
--> statement-breakpoint
CREATE TABLE "AspNetUsers" (
	"Id" text PRIMARY KEY NOT NULL,
	"FullName" varchar(70) NOT NULL,
	"UserName" varchar(256),
	"NormalizedUserName" varchar(256),
	"Email" varchar(256),
	"NormalizedEmail" varchar(256),
	"EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text,
	"SecurityStamp" text,
	"ConcurrencyStamp" text,
	"PhoneNumber" text,
	"PhoneNumberConfirmed" boolean NOT NULL,
	"TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamp with time zone,
	"LockoutEnabled" boolean NOT NULL,
	"AccessFailedCount" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "AspNetUserClaims" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""AspNetUserClaims_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"UserId" text NOT NULL,
	"ClaimType" text,
	"ClaimValue" text
);
--> statement-breakpoint
CREATE TABLE "Categories" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Categories_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Subcategories" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Subcategories_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"CategoryId" integer NOT NULL,
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Customers" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Customers_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Address" varchar(100),
	"City" varchar(50),
	"PostalCode" integer,
	"Phone" varchar(20),
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Orders" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Orders_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"CustomerId" integer NOT NULL,
	"EmployeeId" integer,
	"TotalPrice" numeric,
	"OrderDate" timestamp with time zone NOT NULL,
	"ShippedDate" timestamp with time zone,
	"ShipVia" integer,
	"ShipName" varchar(50) NOT NULL,
	"ShipAddress" varchar(50) NOT NULL,
	"ShipCity" varchar(50) NOT NULL,
	"ShipPostalCode" integer,
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Products" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Products_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Description" varchar(200),
	"Price" numeric,
	"Amount" integer,
	"Sold" integer,
	"IsDeleted" boolean,
	"CategoryId" integer NOT NULL,
	"SubcategoryId" integer NOT NULL,
	"SupplierId" integer,
	"ImageUrl" varchar(100),
	"Image" "bytea",
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "Suppliers" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Suppliers_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"Name" varchar(50) NOT NULL,
	"Contact" varchar(50) NOT NULL,
	"Address" varchar(50),
	"City" varchar(50),
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "OrderDetails" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""OrderDetails_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"OrderId" integer NOT NULL,
	"ProductId" integer NOT NULL,
	"UnitPrice" numeric NOT NULL,
	"Quantity" integer NOT NULL,
	"TimeOfOrder" timestamp with time zone NOT NULL,
	"Discount" numeric,
	"Created" timestamp with time zone NOT NULL,
	"CreatedBy" text,
	"LastModified" timestamp with time zone NOT NULL,
	"LastModifiedBy" text
);
--> statement-breakpoint
CREATE TABLE "AspNetUserRoles" (
	"UserId" text NOT NULL,
	"RoleId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY("UserId","RoleId")
);
--> statement-breakpoint
CREATE TABLE "OrderProduct" (
	"OrdersId" integer NOT NULL,
	"ProductsId" integer NOT NULL,
	CONSTRAINT "PK_OrderProduct" PRIMARY KEY("OrdersId","ProductsId")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text,
	"UserId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY("LoginProvider","ProviderKey")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserTokens" (
	"UserId" text NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY("UserId","LoginProvider","Name")
);
--> statement-breakpoint
ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_Employees_SuperiorId" FOREIGN KEY ("SuperiorId") REFERENCES "public"."Employees"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Subcategories" ADD CONSTRAINT "FK_Subcategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "public"."Categories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "public"."Customers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "public"."Employees"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "public"."Categories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Subcategories_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES "public"."Subcategories"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "public"."Suppliers"("Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "public"."Orders"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "public"."Products"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "OrderProduct" ADD CONSTRAINT "FK_OrderProduct_Orders_OrdersId" FOREIGN KEY ("OrdersId") REFERENCES "public"."Orders"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "OrderProduct" ADD CONSTRAINT "FK_OrderProduct_Products_ProductsId" FOREIGN KEY ("ProductsId") REFERENCES "public"."Products"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IX_Employees_SuperiorId" ON "Employees" USING btree ("SuperiorId" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" USING btree ("NormalizedName" text_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" USING btree ("RoleId" text_ops);--> statement-breakpoint
CREATE INDEX "EmailIndex" ON "AspNetUsers" USING btree ("NormalizedEmail" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" USING btree ("NormalizedUserName" text_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" USING btree ("UserId" text_ops);--> statement-breakpoint
CREATE INDEX "IX_Subcategories_CategoryId" ON "Subcategories" USING btree ("CategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Orders_CustomerId" ON "Orders" USING btree ("CustomerId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Orders_EmployeeId" ON "Orders" USING btree ("EmployeeId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_CategoryId" ON "Products" USING btree ("CategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_SubcategoryId" ON "Products" USING btree ("SubcategoryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_Products_SupplierId" ON "Products" USING btree ("SupplierId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_OrderDetails_OrderId" ON "OrderDetails" USING btree ("OrderId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_OrderDetails_ProductId" ON "OrderDetails" USING btree ("ProductId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" USING btree ("RoleId" text_ops);--> statement-breakpoint
CREATE INDEX "IX_OrderProduct_ProductsId" ON "OrderProduct" USING btree ("ProductsId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" USING btree ("UserId" text_ops);
*/